twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
